    - name: Setup Gradle Wrapper
      run: gradle wrapper

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Debug APK
      run: ./gradlew assembleDebug
